INSERT INTO website_contents (
    key,
    type,
    placement,
    title,
    subtitle,
    body,
    image_url,
    link_url,
    link_label,
    sort_order,
    is_active,
    metadata
) VALUES
(
    'profile.hero',
    'hero',
    'profile',
    'Bagus A. Setiawan',
    'Backend Developer and Full-Stack Engineer',
    'I build custom systems, SaaS products, backend services, and business applications that are reliable, scalable, and ready for real operations. My focus is turning product requirements into maintainable software that teams can actually use and grow with.',
    '',
    '/#contact',
    'Start a Project',
    10,
    TRUE,
    '{"eyebrow":"Profile","availability":"Available for new projects","initials":"BAS","role":"Backend Developer","note":"Custom software, SaaS platforms, workflow automation, and API systems built for dependable business execution.","stats":[{"label":"Experience","value":"6+ years"},{"label":"Core Focus","value":"Backend + SaaS"},{"label":"Location","value":"Bandung Barat, Indonesia"}],"contacts":[{"icon":"phone","label":"Phone","value":"+62 81224173721"},{"icon":"email","label":"Email","value":"braditya12@gmail.com"},{"icon":"web","label":"GitHub","value":"Bagus Setiawan"}]}'::jsonb
),
(
    'profile.about',
    'profile',
    'profile',
    'Professional profile',
    'About',
    'I specialize in backend development, full-stack delivery, and product systems that support real business operations.',
    '',
    '',
    '',
    20,
    TRUE,
    '{"paragraphs":["I have worked across banking, HR, recruitment, billing, calibration, and internal enterprise systems, which has shaped a practical approach to software architecture.","I am comfortable working from feature planning to implementation, integrating APIs, managing data flows, and refining systems for maintainability and scale."]}'::jsonb
),
(
    'profile.capabilities',
    'profile',
    'profile',
    'What I can build',
    'Capabilities',
    'Custom systems, SaaS products, backend services, and admin platforms.',
    '',
    '',
    '',
    30,
    TRUE,
    '{"items":[{"title":"Custom system development"},{"title":"SaaS product delivery"},{"title":"Admin dashboards"},{"title":"REST APIs"},{"title":"Microservices"},{"title":"Database design"},{"title":"Automation"},{"title":"Integration work"}]}'::jsonb
),
(
    'profile.projects',
    'profile',
    'profile',
    'Selected work',
    'Projects',
    'A few project highlights from the resume, presented with a more polished and business-friendly narrative.',
    '',
    '',
    '',
    40,
    TRUE,
    '{"items":[{"title":"One Employee","description":"HR employee management system with API integration, unit testing, and daily workflow support.","image_url":"/images/saas-dashboard-preview.png","tags":["React.js","NestJS","MongoDB"],"sort_order":10},{"title":"Nextrans","description":"Transfer system enhancements with S3 storage, cron jobs, and support for same-bank and interbank flows.","image_url":"/images/saas-dashboard-preview.png","tags":["RabbitMQ","NestJS","Express.js"],"sort_order":20},{"title":"Laboratory Calibration System","description":"Web app for calibration operations with PDF conversion, customer email workflows, and storage integration.","image_url":"/images/saas-dashboard-preview.png","tags":["React.js","Express.js","PostgreSQL","S3"],"sort_order":30}]}'::jsonb
),
(
    'profile.experience',
    'profile',
    'profile',
    'Work history',
    'Experience',
    'Timeline rewritten into clear, professional English.',
    '',
    '',
    '',
    50,
    TRUE,
    '{"items":[{"role":"Backend Developer","company":"PT Kreigen Digital Wesel","period":"July 2023 - Present","summary":"Implemented a robust intrabank transfer system and integrated external banking APIs for interbank transactions.","details":["Golang","TypeScript","NestJS","Express.js","Microservices","REST APIs"],"sort_order":10},{"role":"Full-Stack Developer","company":"PT Lautan Luas Tbk","period":"November 2024 - December 2025","summary":"Developed and maintained internal HR systems, including payroll and recruitment modules, with a scalable API architecture.","details":["NestJS","Express.js","Golang","TypeScript","Microservices"],"sort_order":20},{"role":"Freelance Full-Stack Developer","company":"CV Triwikarma","period":"April 2023 - February 2024","summary":"Collaborated with the team to improve features, add laboratory calibration support, and integrate PDAM Bogor billing.","details":["JavaScript","PHP","Laravel","Redis","S3","Mailgun","MySQL","MongoDB"],"sort_order":30},{"role":"Full-Stack Developer","company":"PT Asian Technology Solution","period":"November 2022 - April 2023","summary":"Revamped the Traveloka career site, implemented mailing workflows, and integrated third-party recruitment platforms.","details":["JavaScript","Next.js","AdonisJS","REST APIs"],"sort_order":40}]}'::jsonb
),
(
    'profile.skills',
    'profile',
    'profile',
    'Technical stack',
    'Skills',
    'Languages, frameworks, and infrastructure tools.',
    '',
    '',
    '',
    60,
    TRUE,
    '{"items":[{"title":"Golang"},{"title":"TypeScript"},{"title":"JavaScript"},{"title":"PHP"},{"title":"NestJS"},{"title":"Express.js"},{"title":"Laravel"},{"title":"React.js"},{"title":"Next.js"},{"title":"PostgreSQL"},{"title":"MySQL"},{"title":"MongoDB"},{"title":"Redis"},{"title":"RabbitMQ"},{"title":"S3"},{"title":"Docker"},{"title":"REST APIs"},{"title":"Microservices"}]}'::jsonb
),
(
    'profile.contact',
    'profile',
    'profile',
    'Open for new work',
    'Contact',
    'Ready to support new custom system or SaaS development projects.',
    '',
    '',
    '',
    70,
    TRUE,
    '{"items":[{"icon":"location","value":"Bandung Barat, Indonesia"},{"icon":"email","value":"braditya12@gmail.com"},{"icon":"phone","value":"+62 81224173721"}]}'::jsonb
)
ON CONFLICT (key) DO UPDATE SET
    type = EXCLUDED.type,
    placement = EXCLUDED.placement,
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    body = EXCLUDED.body,
    image_url = EXCLUDED.image_url,
    link_url = EXCLUDED.link_url,
    link_label = EXCLUDED.link_label,
    sort_order = EXCLUDED.sort_order,
    is_active = EXCLUDED.is_active,
    metadata = EXCLUDED.metadata,
    deleted_at = NULL,
    updated_at = NOW();
