INSERT INTO website_contents (
    key,
    type,
    placement,
    title,
    subtitle,
    body,
    image_url,
    link_url,
    link_label,
    sort_order,
    is_active,
    metadata
) VALUES
(
    'home.blogs',
    'blog-grid',
    'home',
    'Latest insights for building better digital systems.',
    'Blogs',
    'Read practical notes about custom software, SaaS products, managed websites, backend APIs, and workflow automation for growing businesses.',
    '',
    '/blogs',
    'Read Blogs',
    45,
    TRUE,
    '{"items":[{"title":"Why custom software can be better than generic tools","subtitle":"Custom software","description":"Learn when a tailored system is worth building and how it can support real business workflows.","link_label":"Read article","link_url":"/blogs/why-custom-software-fits-business-workflows","image_url":"/images/saas-dashboard-preview.png","sort_order":10},{"title":"How to plan a SaaS MVP without overbuilding","subtitle":"SaaS development","description":"A practical way to define first-version SaaS scope, user roles, dashboards, and backend foundations.","link_label":"Read article","link_url":"/blogs/how-to-plan-saas-mvp","image_url":"/images/saas-dashboard-preview.png","sort_order":20},{"title":"Why company profile websites need CMS control","subtitle":"Website growth","description":"Static company profiles are limiting. Managed content helps websites grow with services, products, and campaigns.","link_label":"Read article","link_url":"/blogs/company-profile-website-with-cms","image_url":"/images/saas-dashboard-preview.png","sort_order":30}]}'::jsonb
),
(
    'blogs.hero',
    'hero',
    'blogs',
    'Practical Blogs for Custom Software, SaaS, Websites, and Automation',
    'Insights for better digital operations',
    'Explore articles that help businesses understand how to plan, build, and grow reliable digital systems with cleaner workflows and stronger technical foundations.',
    '/images/saas-dashboard-preview.png',
    '/#contact',
    'Discuss Your Project',
    10,
    TRUE,
    '{"eyebrow":"Blogs","stats":[{"label":"Topics","value":"Software"},{"label":"Focus","value":"Business Use"},{"label":"Goal","value":"Better Systems"}]}'::jsonb
),
(
    'blogs.grid',
    'blog-grid',
    'blogs',
    'Articles for Business Owners, Founders, and Teams',
    'Featured reading',
    'These articles are designed to explain practical technology decisions in plain business language, from custom systems to SaaS product foundations.',
    '',
    '/#contact',
    'Ask for Advice',
    20,
    TRUE,
    '{"items":[{"title":"Why custom software can be better than generic tools","subtitle":"Custom software","description":"Understand when generic tools become limiting and when a custom system can improve operations, reporting, and team control.","link_label":"Read article","link_url":"/blogs/why-custom-software-fits-business-workflows","image_url":"/images/saas-dashboard-preview.png","sort_order":10},{"title":"How to plan a SaaS MVP without overbuilding","subtitle":"SaaS development","description":"A practical guide to defining MVP scope, user roles, core dashboards, backend APIs, and a roadmap for future SaaS growth.","link_label":"Read article","link_url":"/blogs/how-to-plan-saas-mvp","image_url":"/images/saas-dashboard-preview.png","sort_order":20},{"title":"Why company profile websites need CMS control","subtitle":"Website CMS","description":"Learn why managed content, service pages, product pages, SEO metadata, and contact flows make a company website more useful.","link_label":"Read article","link_url":"/blogs/company-profile-website-with-cms","image_url":"/images/saas-dashboard-preview.png","sort_order":30},{"title":"What makes a backend API reliable for business systems?","subtitle":"Backend API","description":"Explore the backend foundations that support secure access, clean data, integrations, caching, and maintainable product growth.","link_label":"Read article","link_url":"/blogs/reliable-backend-api-for-business-systems","image_url":"/images/saas-dashboard-preview.png","sort_order":40},{"title":"Workflow automation ideas for growing teams","subtitle":"Automation","description":"See practical automation opportunities for repeated tasks, notifications, integrations, scheduled jobs, and operational reporting.","link_label":"Read article","link_url":"/blogs/workflow-automation-ideas","image_url":"/images/saas-dashboard-preview.png","sort_order":50}]}'::jsonb
),
(
    'blogs.contact',
    'section',
    'blogs',
    'Need Help Turning an Idea Into a System?',
    'Contact Us',
    'Share the problem you want to solve. We can help translate it into a practical software, website, SaaS, or automation plan.',
    '',
    '',
    '',
    30,
    TRUE,
    '{"tone":"contact"}'::jsonb
),
(
    'blogs.why-custom-software-fits-business-workflows.hero',
    'hero',
    'blogs/why-custom-software-fits-business-workflows',
    'Why Custom Software Can Fit Business Workflows Better Than Generic Tools',
    'Custom software',
    'Generic tools are useful at the beginning, but growing operations often need software that follows real workflows, roles, data, and reporting needs.',
    '/images/saas-dashboard-preview.png',
    '/services/custom-software-development',
    'View Custom Software Service',
    10,
    TRUE,
    '{"eyebrow":"Custom Software Article","stats":[{"label":"Topic","value":"Operations"},{"label":"Best For","value":"Growing Teams"},{"label":"Output","value":"Custom System"}]}'::jsonb
),
(
    'blogs.why-custom-software-fits-business-workflows.content',
    'blog-post',
    'blogs/why-custom-software-fits-business-workflows',
    'When a Custom System Starts to Make Sense',
    'Article',
    'A custom system becomes valuable when your team spends too much time adapting the business to the tool instead of using software that supports the business process. This usually appears as repeated manual work, scattered spreadsheets, unclear approvals, slow reporting, or duplicated data across multiple platforms.',
    '',
    '/use-cases/custom-business-operations',
    'See Related Use Case',
    20,
    TRUE,
    '{"items":[{"title":"The workflow is specific to your business","subtitle":"Signal 01","description":"If your process includes custom approvals, unique statuses, special documents, or team-specific responsibilities, generic tools may create workarounds instead of solving the problem.","sort_order":10},{"title":"Data is spread across too many places","subtitle":"Signal 02","description":"When important business information lives in spreadsheets, chats, emails, and separate apps, a custom system can centralize records and make reporting easier.","sort_order":20},{"title":"Different roles need different controls","subtitle":"Signal 03","description":"Owners, managers, operators, and support teams often need different dashboards and permissions. Custom software can model these responsibilities clearly.","sort_order":30},{"title":"The system needs to grow over time","subtitle":"Signal 04","description":"A maintainable custom platform can start with core modules and expand into integrations, automation, reporting, or SaaS-like features later.","sort_order":40}]}'::jsonb
),
(
    'blogs.why-custom-software-fits-business-workflows.contact',
    'section',
    'blogs/why-custom-software-fits-business-workflows',
    'Want to Check If Your Workflow Needs Custom Software?',
    'Contact Us',
    'Tell us about your current process, users, data, and pain points. We will help identify whether a custom system is the right direction.',
    '',
    '',
    '',
    30,
    TRUE,
    '{"tone":"contact"}'::jsonb
),
(
    'blogs.how-to-plan-saas-mvp.hero',
    'hero',
    'blogs/how-to-plan-saas-mvp',
    'How to Plan a SaaS MVP Without Overbuilding',
    'SaaS development',
    'A SaaS MVP should prove the core product value with the smallest practical feature set, while keeping the backend and product structure ready to grow.',
    '/images/saas-dashboard-preview.png',
    '/services/saas-development',
    'View SaaS Development Service',
    10,
    TRUE,
    '{"eyebrow":"SaaS Article","stats":[{"label":"Stage","value":"MVP"},{"label":"Focus","value":"Core Value"},{"label":"Growth","value":"Scalable"}]}'::jsonb
),
(
    'blogs.how-to-plan-saas-mvp.content',
    'blog-post',
    'blogs/how-to-plan-saas-mvp',
    'A Practical SaaS MVP Planning Flow',
    'Article',
    'Overbuilding is one of the easiest ways to slow down a SaaS product. A better first step is defining the target user, core problem, minimum dashboard, admin controls, data model, and backend APIs needed to validate the product.',
    '',
    '/use-cases/saas-product-launch',
    'See Related Use Case',
    20,
    TRUE,
    '{"items":[{"title":"Start from the user problem","subtitle":"Step 01","description":"Define who the product helps, what painful workflow it improves, and what result users expect from the first version.","sort_order":10},{"title":"Choose the smallest useful workflow","subtitle":"Step 02","description":"Avoid building every possible feature. Focus on the core flow that lets users experience the main product value.","sort_order":20},{"title":"Plan dashboards and admin controls","subtitle":"Step 03","description":"Most SaaS products need user dashboards and internal admin panels to manage users, content, data, requests, or product settings.","sort_order":30},{"title":"Prepare the backend for future modules","subtitle":"Step 04","description":"Even an MVP should have clean API boundaries, authentication, database structure, and an architecture that can support later features.","sort_order":40}]}'::jsonb
),
(
    'blogs.how-to-plan-saas-mvp.contact',
    'section',
    'blogs/how-to-plan-saas-mvp',
    'Planning a SaaS MVP?',
    'Contact Us',
    'Share your product idea, target users, core features, and business model. We can help shape the right first build.',
    '',
    '',
    '',
    30,
    TRUE,
    '{"tone":"contact"}'::jsonb
),
(
    'blogs.company-profile-website-with-cms.hero',
    'hero',
    'blogs/company-profile-website-with-cms',
    'Why Company Profile Websites Need CMS Control',
    'Website CMS',
    'A professional company profile should be more than a static brochure. Managed content helps your website support services, products, SEO pages, campaigns, and contact conversion.',
    '/images/saas-dashboard-preview.png',
    '/services/company-profile-website',
    'View Website Service',
    10,
    TRUE,
    '{"eyebrow":"Website Article","stats":[{"label":"Content","value":"Managed"},{"label":"SEO","value":"Ready"},{"label":"Growth","value":"Flexible"}]}'::jsonb
),
(
    'blogs.company-profile-website-with-cms.content',
    'blog-post',
    'blogs/company-profile-website-with-cms',
    'A Website Should Be Easy to Update and Extend',
    'Article',
    'When a company website grows, the team needs to update sections, add services, launch product pages, change calls to action, improve SEO metadata, and publish campaign content without rebuilding the frontend every time.',
    '',
    '/products/saeprofile',
    'View SAEProfile Product',
    20,
    TRUE,
    '{"items":[{"title":"Content changes should not require code changes","subtitle":"Reason 01","description":"Hero copy, service cards, contact sections, images, and CTAs should be manageable from admin when the business message changes.","sort_order":10},{"title":"Service and product pages need room to grow","subtitle":"Reason 02","description":"A CMS-backed structure makes it easier to add focused pages for services, products, use cases, and future campaigns.","sort_order":20},{"title":"SEO needs consistent metadata and sitemap support","subtitle":"Reason 03","description":"Managed pages can support better titles, descriptions, canonical URLs, and sitemap entries for search visibility.","sort_order":30},{"title":"Contact conversion should be clear","subtitle":"Reason 04","description":"Professional content and focused CTAs help visitors understand what you offer and how to start a conversation.","sort_order":40}]}'::jsonb
),
(
    'blogs.company-profile-website-with-cms.contact',
    'section',
    'blogs/company-profile-website-with-cms',
    'Want a Company Profile Website You Can Manage?',
    'Contact Us',
    'Tell us about your company, services, products, and content needs. We will help prepare a flexible website structure.',
    '',
    '',
    '',
    30,
    TRUE,
    '{"tone":"contact"}'::jsonb
),
(
    'blogs.reliable-backend-api-for-business-systems.hero',
    'hero',
    'blogs/reliable-backend-api-for-business-systems',
    'What Makes a Backend API Reliable for Business Systems?',
    'Backend API',
    'Reliable backend APIs help products stay secure, maintainable, integrated, and ready for real operational usage.',
    '/images/saas-dashboard-preview.png',
    '/services/backend-api-development',
    'View Backend API Service',
    10,
    TRUE,
    '{"eyebrow":"Backend Article","stats":[{"label":"Security","value":"Auth"},{"label":"Data","value":"Structured"},{"label":"Scale","value":"Ready"}]}'::jsonb
),
(
    'blogs.reliable-backend-api-for-business-systems.content',
    'blog-post',
    'blogs/reliable-backend-api-for-business-systems',
    'Backend Reliability Starts Before Coding',
    'Article',
    'A reliable backend is not only about endpoints. It includes clear data models, authentication, access control, validation, error handling, caching, integrations, logs, and deployment-ready configuration.',
    '',
    '/use-cases/workflow-automation',
    'See Related Use Case',
    20,
    TRUE,
    '{"items":[{"title":"Clear API contracts","subtitle":"Foundation","description":"Good endpoints use predictable request and response structures so frontend, mobile, and integrations can depend on them.","sort_order":10},{"title":"Secure authentication and permissions","subtitle":"Security","description":"Access tokens, refresh tokens, protected routes, and role-based permissions protect business data and admin actions.","sort_order":20},{"title":"Practical database design","subtitle":"Data","description":"The database should match business entities, workflow states, ownership, reporting needs, and future modules.","sort_order":30},{"title":"Caching, storage, and integrations","subtitle":"Operations","description":"Reliable systems often need cache control, file storage, third-party APIs, notifications, and background processing.","sort_order":40}]}'::jsonb
),
(
    'blogs.reliable-backend-api-for-business-systems.contact',
    'section',
    'blogs/reliable-backend-api-for-business-systems',
    'Need a Reliable Backend API?',
    'Contact Us',
    'Share your data model, product flow, auth needs, and integration requirements. We can help design the backend architecture.',
    '',
    '',
    '',
    30,
    TRUE,
    '{"tone":"contact"}'::jsonb
),
(
    'blogs.workflow-automation-ideas.hero',
    'hero',
    'blogs/workflow-automation-ideas',
    'Workflow Automation Ideas for Growing Teams',
    'Automation',
    'Automation can reduce repeated work, connect tools, trigger notifications, prepare reports, and help teams operate with fewer manual steps.',
    '/images/saas-dashboard-preview.png',
    '/use-cases/workflow-automation',
    'View Automation Use Case',
    10,
    TRUE,
    '{"eyebrow":"Automation Article","stats":[{"label":"Goal","value":"Less Manual"},{"label":"Connect","value":"Tools"},{"label":"Output","value":"Faster Flow"}]}'::jsonb
),
(
    'blogs.workflow-automation-ideas.content',
    'blog-post',
    'blogs/workflow-automation-ideas',
    'Where Automation Usually Helps First',
    'Article',
    'The best automation opportunities usually appear in tasks that are repeated often, depend on manual reminders, require data movement between tools, or take too long to report.',
    '',
    '/services/backend-api-development',
    'View Backend Service',
    20,
    TRUE,
    '{"items":[{"title":"Status-based notifications","subtitle":"Idea 01","description":"Send messages or email updates when a request changes status, needs approval, is completed, or requires follow-up.","sort_order":10},{"title":"Scheduled reports","subtitle":"Idea 02","description":"Prepare recurring summaries, exports, or checks without waiting for someone to manually collect data.","sort_order":20},{"title":"API data synchronization","subtitle":"Idea 03","description":"Connect systems so important data does not need to be copied between tools by hand.","sort_order":30},{"title":"Admin-triggered workflows","subtitle":"Idea 04","description":"Give operators safe admin actions that trigger backend processes, notifications, file handling, or integration calls.","sort_order":40}]}'::jsonb
),
(
    'blogs.workflow-automation-ideas.contact',
    'section',
    'blogs/workflow-automation-ideas',
    'Want to Automate Repeated Work?',
    'Contact Us',
    'Tell us which tasks are repeated, delayed, or hard to track. We will help identify the automation flow that fits.',
    '',
    '',
    '',
    30,
    TRUE,
    '{"tone":"contact"}'::jsonb
)
ON CONFLICT (key) DO UPDATE SET
    type = EXCLUDED.type,
    placement = EXCLUDED.placement,
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    body = EXCLUDED.body,
    image_url = EXCLUDED.image_url,
    link_url = EXCLUDED.link_url,
    link_label = EXCLUDED.link_label,
    sort_order = EXCLUDED.sort_order,
    is_active = EXCLUDED.is_active,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();
