INSERT INTO website_contents (
    key,
    type,
    placement,
    title,
    subtitle,
    body,
    image_url,
    link_url,
    link_label,
    sort_order,
    is_active,
    metadata
) VALUES
(
    'about-us.hero',
    'hero',
    'about-us',
    'A technology partner for custom systems, SaaS products, and reliable digital operations.',
    'About SAE Technology Solution',
    'We help businesses turn operational needs into practical, maintainable, and production-ready software. Our work focuses on clear architecture, honest collaboration, and systems that can grow with real business demand.',
    '/images/saas-dashboard-preview.png',
    '/#contact',
    'Discuss a Project',
    10,
    TRUE,
    '{"tone":"trust","items":[{"title":"Custom System Development","description":"Business-specific software built around your workflow, team roles, data, and operational goals.","sort_order":10},{"title":"SaaS Product Implementation","description":"From product foundation to dashboards, APIs, subscriptions, and deployment preparation.","sort_order":20},{"title":"Long-term Technical Support","description":"Clean code, documentation-minded delivery, and improvement paths for future requirements.","sort_order":30}]}'::jsonb
),
(
    'about-us.mission',
    'section',
    'about-us',
    'We build software that makes operations easier to run, measure, and improve.',
    'Our mission',
    'SAE Technology Solution exists to help teams replace scattered manual work with reliable digital systems. We design and develop websites, internal dashboards, backend APIs, custom applications, and SaaS foundations that support real business workflows.',
    '',
    '/products',
    'Explore Products',
    20,
    TRUE,
    '{"items":[{"title":"Business-first discovery","subtitle":"Understand before building","description":"We start by clarifying your workflow, users, business rules, data, integrations, and success criteria.","sort_order":10},{"title":"Scalable engineering","subtitle":"Built to grow","description":"We prioritize maintainable architecture, API clarity, secure access patterns, and deployment-aware implementation.","sort_order":20},{"title":"Professional delivery","subtitle":"Ready for real use","description":"Every implementation is shaped for usability, reliability, and future iteration instead of one-time visuals only.","sort_order":30},{"title":"Flexible collaboration","subtitle":"Ready for requests","description":"We can support new systems, feature extensions, SaaS products, landing pages, admin panels, integrations, and automation workflows.","sort_order":40}]}'::jsonb
),
(
    'about-us.process',
    'banner',
    'about-us',
    'From idea to production-ready system, we keep the process clear.',
    'How we work',
    'We align on scope, design the right architecture, build iteratively, validate with your operational needs, and prepare the system for launch and future improvement.',
    '/images/saas-dashboard-preview.png',
    '/#contact',
    'Start Consultation',
    30,
    TRUE,
    '{"items":[{"title":"Discovery and scope","description":"Define goals, users, roles, data, integrations, and priorities.","sort_order":10},{"title":"Architecture and UI planning","description":"Map pages, APIs, database needs, admin workflows, and delivery phases.","sort_order":20},{"title":"Implementation and review","description":"Build, test, refine, and prepare a maintainable release path.","sort_order":30}]}'::jsonb
),
(
    'about-us.trust',
    'section',
    'about-us',
    'Why clients can trust the way we build.',
    'Quality principles',
    'Trust is built through clarity, consistency, and technical decisions that protect the product beyond launch.',
    '',
    '',
    '',
    40,
    TRUE,
    '{"items":[{"title":"Transparent communication","description":"Clear priorities, practical recommendations, and no unnecessary technical noise.","sort_order":10},{"title":"Security-minded implementation","description":"Authentication, access control, input validation, and data handling are considered from the start.","sort_order":20},{"title":"Maintainable codebase","description":"We structure systems so new requests, modules, and content changes can be added without rebuilding everything.","sort_order":30},{"title":"Content-managed pages","description":"Important website sections can be controlled from admin content placements instead of hardcoded pages.","sort_order":40}]}'::jsonb
),
(
    'about-us.contact',
    'section',
    'about-us',
    'Contact us to plan your next system.',
    'Contact Us',
    'Tell us what you want to build, improve, automate, or launch. We are ready to receive requests for new systems, custom workflows, SaaS products, and professional website development.',
    '',
    '',
    '',
    50,
    TRUE,
    '{"tone":"contact"}'::jsonb
),
(
    'products.saecommerce.solution',
    'section',
    'products/saecommerce',
    'SAECommerce can be shaped around your sales process, not the other way around.',
    'Managed product section',
    'This product page section is controlled from Website Content using placement products/saecommerce. Use it to explain product value, implementation scope, integrations, or industry-specific positioning without changing frontend code.',
    '',
    '/#contact',
    'Request SAECommerce',
    10,
    TRUE,
    '{"items":[{"title":"Product catalog and order workflow","description":"Manage products, orders, customers, payments, and fulfillment steps in a single operational flow.","sort_order":10},{"title":"Admin dashboard and roles","description":"Create internal controls for teams, operators, managers, branches, or business units.","sort_order":20},{"title":"Custom integrations","description":"Connect payment gateways, notifications, reporting, storage, logistics, or existing internal tools.","sort_order":30},{"title":"SaaS-ready foundation","description":"Extend the system toward subscriptions, tenant-aware data, and scalable product operations.","sort_order":40}]}'::jsonb
),
(
    'products.saecommerce.delivery',
    'banner',
    'products/saecommerce',
    'Launch a commerce system with the flexibility of custom development.',
    'Professional delivery',
    'SAECommerce is suitable for businesses that need a serious ecommerce foundation, custom B2B ordering, internal commerce operations, or a SaaS product built on top of proven modules.',
    '/images/saas-dashboard-preview.png',
    '/#contact',
    'Plan Implementation',
    20,
    TRUE,
    '{"tone":"product"}'::jsonb
),
(
    'products.saecommerce.contact',
    'section',
    'products/saecommerce',
    'Contact us to customize SAECommerce for your business.',
    'Contact Us',
    'Share your product flow, payment needs, integration requirements, admin roles, and launch timeline. We will help recommend the right build plan.',
    '',
    '',
    '',
    30,
    TRUE,
    '{"tone":"contact"}'::jsonb
)
ON CONFLICT (key) DO UPDATE SET
    type = EXCLUDED.type,
    placement = EXCLUDED.placement,
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    body = EXCLUDED.body,
    image_url = EXCLUDED.image_url,
    link_url = EXCLUDED.link_url,
    link_label = EXCLUDED.link_label,
    sort_order = EXCLUDED.sort_order,
    is_active = EXCLUDED.is_active,
    metadata = EXCLUDED.metadata,
    deleted_at = NULL,
    updated_at = NOW();
