INSERT INTO website_contents (
    key,
    type,
    placement,
    title,
    subtitle,
    body,
    image_url,
    link_url,
    link_label,
    sort_order,
    is_active,
    metadata
) VALUES
(
    'home.use-cases',
    'use-case-grid',
    'home',
    'Practical use cases for systems your business can actually use.',
    'Use cases',
    'Explore how custom apps, websites, automation, and SaaS products can be shaped into real business workflows, not just generic software pages.',
    '',
    '/use-cases',
    'Explore Use Cases',
    35,
    TRUE,
    '{"items":[{"title":"Custom business operations","subtitle":"Custom apps","description":"Replace spreadsheet-heavy or manual workflows with role-based systems, dashboards, approvals, reports, and data control.","link_label":"View use case","link_url":"/use-cases/custom-business-operations","image_url":"/images/saas-dashboard-preview.png","sort_order":10},{"title":"Professional website growth","subtitle":"Websites","description":"Turn your company website into a content-managed growth channel with service pages, product pages, SEO content, and contact funnels.","link_label":"View use case","link_url":"/use-cases/professional-website-growth","image_url":"/images/saas-dashboard-preview.png","sort_order":20},{"title":"Workflow automation","subtitle":"Automation","description":"Reduce repeated manual work through API integrations, notifications, admin workflows, scheduled processes, and connected business data.","link_label":"View use case","link_url":"/use-cases/workflow-automation","image_url":"/images/saas-dashboard-preview.png","sort_order":30},{"title":"SaaS product launch","subtitle":"SaaS products","description":"Build MVP-ready SaaS foundations with dashboards, user roles, backend APIs, admin controls, content pages, and scalable product structure.","link_label":"View use case","link_url":"/use-cases/saas-product-launch","image_url":"/images/saas-dashboard-preview.png","sort_order":40}]}'::jsonb
),
(
    'use-cases.hero',
    'hero',
    'use-cases',
    'Use Cases for Custom Apps, Websites, Automation, and SaaS Products',
    'From homepage promise to practical implementation',
    'See how SAE Technology Solution can turn common business needs into practical systems: cleaner workflows, managed websites, automation, backend APIs, and SaaS-ready products.',
    '/images/saas-dashboard-preview.png',
    '/#contact',
    'Discuss Your Use Case',
    10,
    TRUE,
    '{"eyebrow":"Use Cases","stats":[{"label":"Focus","value":"Real Workflows"},{"label":"Delivery","value":"Custom Systems"},{"label":"Growth","value":"SaaS Ready"}]}'::jsonb
),
(
    'use-cases.grid',
    'use-case-grid',
    'use-cases',
    'Choose the Use Case That Matches Your Business Need',
    'What we solve',
    'These use cases are aligned with the homepage promise: custom apps, professional websites, workflow automation, and SaaS products that support real operations.',
    '',
    '/#contact',
    'Request Recommendation',
    20,
    TRUE,
    '{"items":[{"title":"Custom business operations","subtitle":"Internal systems","description":"For businesses that need dashboards, approvals, roles, reports, and workflow control instead of disconnected spreadsheets or generic tools.","link_label":"Explore use case","link_url":"/use-cases/custom-business-operations","image_url":"/images/saas-dashboard-preview.png","sort_order":10},{"title":"Professional website growth","subtitle":"Content-managed website","description":"For companies that need a professional website with admin-managed sections, SEO-ready service pages, product pages, and contact conversion paths.","link_label":"Explore use case","link_url":"/use-cases/professional-website-growth","image_url":"/images/saas-dashboard-preview.png","sort_order":20},{"title":"Workflow automation","subtitle":"Less manual work","description":"For teams that repeat the same operational steps and need integrations, notifications, scheduled tasks, connected data, and admin workflows.","link_label":"Explore use case","link_url":"/use-cases/workflow-automation","image_url":"/images/saas-dashboard-preview.png","sort_order":30},{"title":"SaaS product launch","subtitle":"Product foundation","description":"For founders or businesses that want to launch a SaaS product with clear MVP scope, backend APIs, dashboards, roles, and growth-ready structure.","link_label":"Explore use case","link_url":"/use-cases/saas-product-launch","image_url":"/images/saas-dashboard-preview.png","sort_order":40}]}'::jsonb
),
(
    'use-cases.fit',
    'process',
    'use-cases',
    'How We Match a Use Case to the Right Build',
    'Decision flow',
    'A good system starts by matching business problems to the right technical scope, not by forcing every request into the same template.',
    '',
    '/services',
    'View Services',
    30,
    TRUE,
    '{"items":[{"title":"Identify the operational problem","subtitle":"Step 01","description":"Clarify what is slow, repeated, difficult to measure, hard to manage, or risky in the current process.","sort_order":10},{"title":"Map the users and workflow","subtitle":"Step 02","description":"Understand who uses the system, what data they manage, and what approvals or outputs matter.","sort_order":20},{"title":"Choose the right implementation","subtitle":"Step 03","description":"Decide whether the need fits a website, custom app, automation flow, backend API, SaaS product, or combined system.","sort_order":30},{"title":"Build with future requests in mind","subtitle":"Step 04","description":"Structure the content, API, admin panel, and data model so the system can grow after launch.","sort_order":40}]}'::jsonb
),
(
    'use-cases.contact',
    'section',
    'use-cases',
    'Not Sure Which Use Case Fits?',
    'Contact Us',
    'Tell us what you want to improve, automate, launch, or manage. We can help translate the business need into a clear system plan.',
    '',
    '',
    '',
    40,
    TRUE,
    '{"tone":"contact"}'::jsonb
),
(
    'use-cases.custom-business-operations.hero',
    'hero',
    'use-cases/custom-business-operations',
    'Custom Business Operations System',
    'Use case: custom apps',
    'For businesses that need cleaner internal workflows, role-based dashboards, structured data, approvals, reports, and operational visibility beyond spreadsheets or generic tools.',
    '/images/saas-dashboard-preview.png',
    '/services/custom-software-development',
    'View Related Service',
    10,
    TRUE,
    '{"eyebrow":"Operational System","stats":[{"label":"Best For","value":"Internal Teams"},{"label":"Output","value":"Dashboards"},{"label":"Control","value":"Roles"}]}'::jsonb
),
(
    'use-cases.custom-business-operations.problem',
    'use-case-detail',
    'use-cases/custom-business-operations',
    'When This Use Case Makes Sense',
    'Business problem',
    'This is ideal when a team manages important data manually, repeats the same approval steps, struggles with reporting, or needs one controlled place for operations.',
    '',
    '/#contact',
    'Plan Operational System',
    20,
    TRUE,
    '{"items":[{"title":"Manual workflow overload","subtitle":"Pain point","description":"Data is scattered across spreadsheets, chats, files, and repeated manual updates.","sort_order":10},{"title":"Unclear ownership","subtitle":"Team control","description":"Different team members need different access, actions, approvals, and dashboards.","sort_order":20},{"title":"Slow reporting","subtitle":"Visibility","description":"Managers need clearer reports, status tracking, and searchable operational records.","sort_order":30},{"title":"Hard to scale process","subtitle":"Growth","description":"The current workflow works only while the team is small and becomes risky as volume grows.","sort_order":40}]}'::jsonb
),
(
    'use-cases.custom-business-operations.solution',
    'process',
    'use-cases/custom-business-operations',
    'What We Can Build',
    'Solution scope',
    'The implementation can be shaped around your actual workflow and connected to future modules when needed.',
    '',
    '',
    '',
    30,
    TRUE,
    '{"items":[{"title":"Role-based dashboard","subtitle":"Module","description":"Give each user the right view, actions, and permissions for their responsibility.","sort_order":10},{"title":"Workflow and approval flow","subtitle":"Module","description":"Convert repeated business rules into statuses, forms, validations, and review steps.","sort_order":20},{"title":"Reports and searchable records","subtitle":"Module","description":"Make operational data easier to find, filter, export, and understand.","sort_order":30},{"title":"Integrations and notifications","subtitle":"Module","description":"Connect APIs, storage, email, alerts, or existing systems when the workflow needs it.","sort_order":40}]}'::jsonb
),
(
    'use-cases.custom-business-operations.contact',
    'section',
    'use-cases/custom-business-operations',
    'Need a System for Your Operation?',
    'Contact Us',
    'Share your workflow, users, data, and current pain points. We will help shape a practical custom system plan.',
    '',
    '',
    '',
    40,
    TRUE,
    '{"tone":"contact"}'::jsonb
),
(
    'use-cases.professional-website-growth.hero',
    'hero',
    'use-cases/professional-website-growth',
    'Professional Website Growth With Managed Content',
    'Use case: websites',
    'For companies that want their website to support credibility, SEO, service explanation, product pages, campaign pages, and contact conversion without editing frontend code.',
    '/images/saas-dashboard-preview.png',
    '/services/company-profile-website',
    'View Related Service',
    10,
    TRUE,
    '{"eyebrow":"Website Growth","stats":[{"label":"Content","value":"Managed"},{"label":"SEO","value":"Ready"},{"label":"Pages","value":"Flexible"}]}'::jsonb
),
(
    'use-cases.professional-website-growth.problem',
    'use-case-detail',
    'use-cases/professional-website-growth',
    'When This Use Case Makes Sense',
    'Business problem',
    'A static website is often not enough when a business needs to explain services clearly, launch product pages, update sections, collect inquiries, and grow search visibility.',
    '',
    '/#contact',
    'Plan Website Growth',
    20,
    TRUE,
    '{"items":[{"title":"Content is hard to update","subtitle":"Pain point","description":"Teams need to edit copy, sections, CTAs, products, and contact messaging without developer changes every time.","sort_order":10},{"title":"Service pages are missing","subtitle":"SEO gap","description":"The website does not have focused landing pages for important services, products, or business keywords.","sort_order":20},{"title":"Trust signals are unclear","subtitle":"Conversion gap","description":"Visitors need clearer proof, process, service scope, profile information, and calls to action.","sort_order":30},{"title":"Campaign pages are needed","subtitle":"Growth","description":"The business wants future promotional pages, product launches, or industry-specific landing pages.","sort_order":40}]}'::jsonb
),
(
    'use-cases.professional-website-growth.solution',
    'process',
    'use-cases/professional-website-growth',
    'What We Can Build',
    'Solution scope',
    'The website can become a managed growth platform with content placements, product pages, services, use cases, contact sections, and SEO-ready metadata.',
    '',
    '',
    '',
    30,
    TRUE,
    '{"items":[{"title":"Admin-managed website content","subtitle":"Module","description":"Manage hero sections, banners, service grids, use cases, profile content, product pages, and contact sections.","sort_order":10},{"title":"SEO-focused landing pages","subtitle":"Module","description":"Create pages for services, use cases, products, and future campaigns with metadata and sitemap support.","sort_order":20},{"title":"Professional brand settings","subtitle":"Module","description":"Control logo, colors, contrast, typography, labels, shadows, and imagery from website settings.","sort_order":30},{"title":"Contact conversion flow","subtitle":"Module","description":"Use clear CTAs and captcha-protected contact forms to receive business inquiries.","sort_order":40}]}'::jsonb
),
(
    'use-cases.professional-website-growth.contact',
    'section',
    'use-cases/professional-website-growth',
    'Want a Website That Can Grow?',
    'Contact Us',
    'Tell us about your company, services, products, content needs, and target audience. We will help plan the right website structure.',
    '',
    '',
    '',
    40,
    TRUE,
    '{"tone":"contact"}'::jsonb
),
(
    'use-cases.workflow-automation.hero',
    'hero',
    'use-cases/workflow-automation',
    'Workflow Automation for Repeated Business Tasks',
    'Use case: automation',
    'For teams that spend too much time repeating the same operational steps and need connected data, notifications, scheduled processes, integrations, and admin-managed workflows.',
    '/images/saas-dashboard-preview.png',
    '/services/backend-api-development',
    'View Related Service',
    10,
    TRUE,
    '{"eyebrow":"Workflow Automation","stats":[{"label":"Goal","value":"Less Manual"},{"label":"Connect","value":"APIs"},{"label":"Control","value":"Admin Flow"}]}'::jsonb
),
(
    'use-cases.workflow-automation.problem',
    'use-case-detail',
    'use-cases/workflow-automation',
    'When This Use Case Makes Sense',
    'Business problem',
    'Automation is useful when the same tasks are repeated daily, data moves between tools manually, notifications are missed, or reports take too long to prepare.',
    '',
    '/#contact',
    'Plan Automation',
    20,
    TRUE,
    '{"items":[{"title":"Repeated data entry","subtitle":"Pain point","description":"Team members enter or copy the same data across multiple systems, documents, or channels.","sort_order":10},{"title":"Manual notifications","subtitle":"Pain point","description":"Important status changes depend on someone remembering to send messages or updates.","sort_order":20},{"title":"Disconnected tools","subtitle":"Integration gap","description":"Existing systems do not talk to each other, causing delays, duplicate work, and unclear status.","sort_order":30},{"title":"Slow operational reporting","subtitle":"Visibility gap","description":"Reports require manual collection, filtering, exports, and repeated formatting.","sort_order":40}]}'::jsonb
),
(
    'use-cases.workflow-automation.solution',
    'process',
    'use-cases/workflow-automation',
    'What We Can Build',
    'Solution scope',
    'Automation can be implemented through backend APIs, scheduled jobs, notifications, admin actions, storage flows, and integrations with existing tools.',
    '',
    '',
    '',
    30,
    TRUE,
    '{"items":[{"title":"API integrations","subtitle":"Module","description":"Connect internal systems, third-party services, payment flows, email, storage, or reporting tools.","sort_order":10},{"title":"Scheduled processes","subtitle":"Module","description":"Run repeated tasks on a schedule, such as reminders, status updates, data checks, or report preparation.","sort_order":20},{"title":"Notification workflows","subtitle":"Module","description":"Send updates through email or other channels when important business events happen.","sort_order":30},{"title":"Admin automation controls","subtitle":"Module","description":"Give operators controlled buttons, statuses, and actions to trigger automated workflow steps safely.","sort_order":40}]}'::jsonb
),
(
    'use-cases.workflow-automation.contact',
    'section',
    'use-cases/workflow-automation',
    'Ready to Reduce Manual Work?',
    'Contact Us',
    'Tell us which repeated tasks slow your team down. We will help identify the automation flow that makes sense.',
    '',
    '',
    '',
    40,
    TRUE,
    '{"tone":"contact"}'::jsonb
),
(
    'use-cases.saas-product-launch.hero',
    'hero',
    'use-cases/saas-product-launch',
    'SaaS Product Launch Foundation',
    'Use case: SaaS products',
    'For founders and businesses that want to launch a SaaS product with a clear MVP, user dashboards, admin controls, backend APIs, content pages, and scalable product architecture.',
    '/images/saas-dashboard-preview.png',
    '/services/saas-development',
    'View Related Service',
    10,
    TRUE,
    '{"eyebrow":"SaaS Launch","stats":[{"label":"Stage","value":"MVP"},{"label":"Product","value":"Dashboard"},{"label":"Growth","value":"Scalable"}]}'::jsonb
),
(
    'use-cases.saas-product-launch.problem',
    'use-case-detail',
    'use-cases/saas-product-launch',
    'When This Use Case Makes Sense',
    'Business problem',
    'A SaaS idea needs more than a landing page. It needs a clear product workflow, backend foundation, admin controls, user access, and a roadmap that can grow after launch.',
    '',
    '/#contact',
    'Plan SaaS Launch',
    20,
    TRUE,
    '{"items":[{"title":"Idea needs MVP structure","subtitle":"Product planning","description":"The product needs a focused first version that solves the core problem without overbuilding.","sort_order":10},{"title":"Users need dashboards","subtitle":"Product flow","description":"Different users need clear pages, actions, access rules, and onboarding flows.","sort_order":20},{"title":"Admin needs control","subtitle":"Operations","description":"Internal teams need to manage users, content, product data, requests, or operational records.","sort_order":30},{"title":"Future monetization matters","subtitle":"Growth","description":"The architecture should be ready for subscriptions, payments, tenant-aware data, and additional modules later.","sort_order":40}]}'::jsonb
),
(
    'use-cases.saas-product-launch.solution',
    'process',
    'use-cases/saas-product-launch',
    'What We Can Build',
    'Solution scope',
    'A SaaS foundation can include product landing pages, authentication, role-based dashboards, admin panels, backend APIs, content management, and growth-ready modules.',
    '',
    '',
    '',
    30,
    TRUE,
    '{"items":[{"title":"MVP feature set","subtitle":"Module","description":"Define and build the first product version with essential user value and clear scope.","sort_order":10},{"title":"User and admin dashboards","subtitle":"Module","description":"Create dashboards for customers, admins, operators, or owners with role-based permissions.","sort_order":20},{"title":"Backend API foundation","subtitle":"Module","description":"Build authentication, refresh token flow, database models, storage, caching, and integration-ready APIs.","sort_order":30},{"title":"Growth-ready content pages","subtitle":"Module","description":"Manage product pages, service content, FAQs, CTAs, and SEO metadata from admin content.","sort_order":40}]}'::jsonb
),
(
    'use-cases.saas-product-launch.contact',
    'section',
    'use-cases/saas-product-launch',
    'Have a SaaS Product to Launch?',
    'Contact Us',
    'Share your product idea, target users, MVP features, and business model. We will help define the build roadmap.',
    '',
    '',
    '',
    40,
    TRUE,
    '{"tone":"contact"}'::jsonb
)
ON CONFLICT (key) DO UPDATE SET
    type = EXCLUDED.type,
    placement = EXCLUDED.placement,
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    body = EXCLUDED.body,
    image_url = EXCLUDED.image_url,
    link_url = EXCLUDED.link_url,
    link_label = EXCLUDED.link_label,
    sort_order = EXCLUDED.sort_order,
    is_active = EXCLUDED.is_active,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();
