INSERT INTO website_contents (
    key,
    type,
    placement,
    title,
    subtitle,
    body,
    image_url,
    link_url,
    link_label,
    sort_order,
    is_active,
    metadata
) VALUES
(
    'services.hero',
    'hero',
    'services',
    'Custom Software and SaaS Development Services',
    'Professional development partner',
    'Build reliable business systems, SaaS products, websites, admin panels, and backend APIs that match your workflow and are ready for real operations.',
    '/images/saas-dashboard-preview.png',
    '/#contact',
    'Discuss Your Project',
    10,
    TRUE,
    '{"eyebrow":"Services","stats":[{"label":"Core Focus","value":"Custom Systems"},{"label":"Delivery","value":"SaaS Ready"},{"label":"Support","value":"Request Ready"}]}'::jsonb
),
(
    'services.grid',
    'service-grid',
    'services',
    'Services Built for Growing Digital Operations',
    'What we can build',
    'Choose a focused service or request a custom implementation plan. Each service page can be managed from Website Content using placement-based sections.',
    '',
    '/#contact',
    'Request Consultation',
    20,
    TRUE,
    '{"items":[{"title":"Custom Software Development","subtitle":"Business system","description":"Tailored internal systems, approval flows, dashboards, reports, roles, and integrations built around your real operational process.","link_label":"View service","link_url":"/services/custom-software-development","image_url":"/images/saas-dashboard-preview.png","sort_order":10},{"title":"SaaS Product Development","subtitle":"Product foundation","description":"Plan, design, and build SaaS platforms with role-based access, admin controls, APIs, tenant-ready structure, and scalable product workflows.","link_label":"View service","link_url":"/services/saas-development","image_url":"/images/saas-dashboard-preview.png","sort_order":20},{"title":"Company Profile Website with CMS","subtitle":"Managed website","description":"Professional company profile websites with admin-managed sections, product pages, SEO content, theme settings, contact forms, and flexible landing pages.","link_label":"View service","link_url":"/services/company-profile-website","image_url":"/images/saas-dashboard-preview.png","sort_order":30},{"title":"Backend API Development","subtitle":"Reliable backend","description":"Secure REST APIs, authentication, database design, file storage, integrations, caching, queues, and backend services for web and mobile products.","link_label":"View service","link_url":"/services/backend-api-development","image_url":"/images/saas-dashboard-preview.png","sort_order":40}]}'::jsonb
),
(
    'services.process',
    'process',
    'services',
    'A Practical Delivery Process',
    'How projects move',
    'Every project starts with clarity, then moves into structured implementation, review, and iteration so the final system is useful beyond the first launch.',
    '',
    '/#contact',
    'Start Discovery',
    30,
    TRUE,
    '{"items":[{"title":"Discovery and scope","subtitle":"Step 01","description":"Clarify users, workflows, data, permissions, integrations, priorities, and success criteria before development starts.","sort_order":10},{"title":"Architecture and content plan","subtitle":"Step 02","description":"Map the system structure, content placements, API boundaries, database model, and implementation roadmap.","sort_order":20},{"title":"Build and review","subtitle":"Step 03","description":"Develop in focused milestones with usable outputs, review points, and practical improvements based on feedback.","sort_order":30},{"title":"Launch and extend","subtitle":"Step 04","description":"Prepare deployment, test critical flows, and keep the foundation ready for new requests, modules, and future growth.","sort_order":40}]}'::jsonb
),
(
    'services.trust',
    'testimonial',
    'services',
    'Built With Backend-First Reliability',
    'Why it works',
    'The service is shaped for businesses that need more than a visual website. We focus on maintainable architecture, admin controls, clear APIs, secure access, and content that can grow.',
    '',
    '/profile',
    'View Profile',
    40,
    TRUE,
    '{"items":[{"title":"Operational thinking","subtitle":"Business first","description":"Features are designed around actual workflows, team roles, data ownership, and daily usage.","sort_order":10},{"title":"Admin-managed content","subtitle":"Flexible control","description":"Pages, sections, product content, services, and contact messaging can be updated without frontend code changes.","sort_order":20},{"title":"Integration ready","subtitle":"Connect systems","description":"Projects can connect APIs, storage, email, payments, dashboards, queues, and existing operational tools.","sort_order":30},{"title":"Future request ready","subtitle":"Expandable foundation","description":"The code and content structure are prepared for new modules, landing pages, and custom requests over time.","sort_order":40}]}'::jsonb
),
(
    'services.contact',
    'section',
    'services',
    'Ready to Plan Your Next System?',
    'Contact Us',
    'Share what you want to build, improve, automate, or launch. We can help turn your requirement into a practical development plan.',
    '',
    '',
    '',
    50,
    TRUE,
    '{"tone":"contact"}'::jsonb
),
(
    'services.custom-software-development.hero',
    'hero',
    'services/custom-software-development',
    'Custom Software Development for Business Operations',
    'Tailored system development',
    'Build a system that follows your business process, not the other way around. We create internal platforms, dashboards, workflows, and integrations designed for daily operational use.',
    '/images/saas-dashboard-preview.png',
    '/#contact',
    'Discuss Custom System',
    10,
    TRUE,
    '{"eyebrow":"Custom Software","stats":[{"label":"Workflow","value":"Tailored"},{"label":"Access","value":"Role Based"},{"label":"Output","value":"Operational"}]}'::jsonb
),
(
    'services.custom-software-development.overview',
    'service-detail',
    'services/custom-software-development',
    'What This Service Covers',
    'Scope',
    'From requirements to release, the service covers business analysis, backend architecture, admin panel development, data modeling, role management, reporting, integrations, and deployment preparation.',
    '',
    '/#contact',
    'Request System Plan',
    20,
    TRUE,
    '{"items":[{"title":"Internal business systems","subtitle":"Operations","description":"Manage approvals, records, users, branches, tasks, reports, and operational workflows in one controlled system.","sort_order":10},{"title":"Admin dashboards","subtitle":"Control center","description":"Create dashboards for owners, operators, managers, and support teams with clear access permissions.","sort_order":20},{"title":"Custom workflows","subtitle":"Process fit","description":"Translate business rules into forms, statuses, notifications, validations, and audit-friendly activity flows.","sort_order":30},{"title":"System integrations","subtitle":"Connected data","description":"Connect existing APIs, storage, email, payment, reporting, or third-party services when needed.","sort_order":40}]}'::jsonb
),
(
    'services.custom-software-development.process',
    'process',
    'services/custom-software-development',
    'Development Approach',
    'How we build',
    'The project is broken down into clear stages so each feature has purpose, ownership, and measurable value before it is released.',
    '',
    '',
    '',
    30,
    TRUE,
    '{"items":[{"title":"Requirement mapping","subtitle":"Step 01","description":"Identify users, data, approvals, reports, existing tools, and operational pain points.","sort_order":10},{"title":"System design","subtitle":"Step 02","description":"Define modules, database structure, API contracts, permissions, and content areas.","sort_order":20},{"title":"Implementation","subtitle":"Step 03","description":"Build backend, frontend, admin flows, validations, integrations, and responsive UI.","sort_order":30},{"title":"Testing and launch","subtitle":"Step 04","description":"Review critical flows, fix issues, prepare deployment, and document how the team should use the system.","sort_order":40}]}'::jsonb
),
(
    'services.custom-software-development.faq',
    'faq',
    'services/custom-software-development',
    'Common Questions',
    'FAQ',
    'Useful answers before starting a custom software project.',
    '',
    '',
    '',
    40,
    TRUE,
    '{"items":[{"title":"Can the system follow our current workflow?","description":"Yes. The goal is to understand your workflow first, then design modules, roles, data, and approvals around it.","sort_order":10},{"title":"Can it be expanded later?","description":"Yes. The system can be structured with scalable modules so new requests can be added after launch.","sort_order":20},{"title":"Can you integrate external APIs?","description":"Yes. We can integrate APIs, file storage, email, payment, reporting, or other internal tools depending on the requirement.","sort_order":30}]}'::jsonb
),
(
    'services.custom-software-development.contact',
    'section',
    'services/custom-software-development',
    'Need a Custom System for Your Business?',
    'Contact Us',
    'Tell us about your workflow, team roles, data, and business rules. We will help define the right implementation scope.',
    '',
    '',
    '',
    50,
    TRUE,
    '{"tone":"contact"}'::jsonb
),
(
    'services.saas-development.hero',
    'hero',
    'services/saas-development',
    'SaaS Product Development From Idea to Launch',
    'SaaS foundation',
    'Turn your SaaS idea into a structured product with admin controls, user workflows, backend APIs, content management, and a foundation ready for future growth.',
    '/images/saas-dashboard-preview.png',
    '/#contact',
    'Plan My SaaS',
    10,
    TRUE,
    '{"eyebrow":"SaaS Development","stats":[{"label":"Product","value":"MVP Ready"},{"label":"Backend","value":"API First"},{"label":"Growth","value":"Scalable"}]}'::jsonb
),
(
    'services.saas-development.overview',
    'service-detail',
    'services/saas-development',
    'What We Can Build for SaaS Products',
    'Product modules',
    'We help design and build SaaS foundations with clear product flows, user roles, onboarding, dashboards, admin content, subscription-ready structure, and API architecture.',
    '',
    '/#contact',
    'Discuss SaaS Scope',
    20,
    TRUE,
    '{"items":[{"title":"MVP product flow","subtitle":"Launch faster","description":"Build the essential user journey, dashboard, admin management, and core product features for validation.","sort_order":10},{"title":"Role-based access","subtitle":"Secure controls","description":"Support owners, admins, teams, customers, or operators with permission-aware workflows.","sort_order":20},{"title":"Admin-managed pages","subtitle":"Content control","description":"Manage landing pages, product sections, FAQs, CTAs, and marketing content from admin.","sort_order":30},{"title":"API and data foundation","subtitle":"Backend ready","description":"Design REST APIs, database models, storage, caching, and integrations for future product modules.","sort_order":40}]}'::jsonb
),
(
    'services.saas-development.process',
    'process',
    'services/saas-development',
    'SaaS Delivery Roadmap',
    'From idea to release',
    'A SaaS project needs more than pages. We plan product scope, user value, backend structure, admin control, and future monetization paths.',
    '',
    '',
    '',
    30,
    TRUE,
    '{"items":[{"title":"Product discovery","subtitle":"Step 01","description":"Clarify users, problem, core value, feature priority, and product assumptions.","sort_order":10},{"title":"MVP scope","subtitle":"Step 02","description":"Define the first usable product with core modules, onboarding, dashboard, and admin control.","sort_order":20},{"title":"Build foundation","subtitle":"Step 03","description":"Develop frontend, backend API, database, authentication, content control, and product workflows.","sort_order":30},{"title":"Prepare growth","subtitle":"Step 04","description":"Keep the architecture ready for subscription, tenant-aware data, analytics, automation, and additional modules.","sort_order":40}]}'::jsonb
),
(
    'services.saas-development.faq',
    'faq',
    'services/saas-development',
    'SaaS Development Questions',
    'FAQ',
    'Helpful notes for founders or businesses planning a SaaS product.',
    '',
    '',
    '',
    40,
    TRUE,
    '{"items":[{"title":"Can you build only the MVP first?","description":"Yes. The first phase can focus on a clear MVP so the product can be validated before adding advanced features.","sort_order":10},{"title":"Can the SaaS support multiple roles?","description":"Yes. Role-based dashboards and permissions can be planned from the beginning.","sort_order":20},{"title":"Can it connect to payments later?","description":"Yes. The foundation can be prepared for payment gateways, subscriptions, invoicing, and customer billing flows.","sort_order":30}]}'::jsonb
),
(
    'services.saas-development.contact',
    'section',
    'services/saas-development',
    'Have a SaaS Idea to Build?',
    'Contact Us',
    'Share the product idea, target users, business model, and first features. We will help shape the development roadmap.',
    '',
    '',
    '',
    50,
    TRUE,
    '{"tone":"contact"}'::jsonb
),
(
    'services.company-profile-website.hero',
    'hero',
    'services/company-profile-website',
    'Company Profile Website With Flexible CMS',
    'Admin-managed website',
    'Create a professional company profile website that your team can manage, extend, and customize for services, products, campaigns, SEO content, and future business requests.',
    '/images/saas-dashboard-preview.png',
    '/#contact',
    'Build Company Profile',
    10,
    TRUE,
    '{"eyebrow":"Company Profile CMS","stats":[{"label":"Content","value":"Managed"},{"label":"Pages","value":"Flexible"},{"label":"SEO","value":"Ready"}]}'::jsonb
),
(
    'services.company-profile-website.overview',
    'service-detail',
    'services/company-profile-website',
    'More Than a Static Company Profile',
    'Website capability',
    'This service is for businesses that want a credible website with flexible content control, professional presentation, product pages, contact forms, theme settings, and landing pages that can grow.',
    '',
    '/products/saeprofile',
    'View SAEProfile',
    20,
    TRUE,
    '{"items":[{"title":"Admin-managed sections","subtitle":"Content control","description":"Update hero sections, service cards, product pages, carousels, CTAs, contact content, and marketing blocks without code changes.","sort_order":10},{"title":"Professional brand settings","subtitle":"Visual system","description":"Manage logo, colors, contrast, labels, fonts, rounded corners, shadows, images, and contact details from admin.","sort_order":20},{"title":"SEO-friendly pages","subtitle":"Search visibility","description":"Use structured service pages, product pages, metadata, sitemap, and content placements for better discoverability.","sort_order":30},{"title":"Future landing pages","subtitle":"Campaign ready","description":"Add placement-based pages for promotions, product launches, industry pages, or custom campaigns.","sort_order":40}]}'::jsonb
),
(
    'services.company-profile-website.process',
    'process',
    'services/company-profile-website',
    'Website Build Process',
    'From content to launch',
    'We organize the website around your business story, services, trust points, and conversion goals.',
    '',
    '',
    '',
    30,
    TRUE,
    '{"items":[{"title":"Brand and content mapping","subtitle":"Step 01","description":"Clarify company positioning, services, target audience, trust points, content needs, and visual direction.","sort_order":10},{"title":"Page structure setup","subtitle":"Step 02","description":"Prepare home, about, profile, services, products, contact, and custom placement sections.","sort_order":20},{"title":"Admin content configuration","subtitle":"Step 03","description":"Set up manageable sections, metadata items, CTAs, theme settings, images, and contact form flow.","sort_order":30},{"title":"SEO and launch review","subtitle":"Step 04","description":"Review metadata, sitemap, responsiveness, content clarity, and conversion paths before publishing.","sort_order":40}]}'::jsonb
),
(
    'services.company-profile-website.faq',
    'faq',
    'services/company-profile-website',
    'Company Profile Website Questions',
    'FAQ',
    'Answers for businesses that need a professional website with content control.',
    '',
    '',
    '',
    40,
    TRUE,
    '{"items":[{"title":"Can we manage the content ourselves?","description":"Yes. The website content is designed to be managed from admin using placement-based sections.","sort_order":10},{"title":"Can we add new pages later?","description":"Yes. New service, product, campaign, or landing pages can be added using website content placements.","sort_order":20},{"title":"Can it show products and contact forms?","description":"Yes. Product pages, contact sections, and captcha-protected contact forms can be included.","sort_order":30}]}'::jsonb
),
(
    'services.company-profile-website.contact',
    'section',
    'services/company-profile-website',
    'Ready to Launch a Better Company Profile?',
    'Contact Us',
    'Tell us about your company, services, brand direction, and content needs. We will help prepare the right website structure.',
    '',
    '',
    '',
    50,
    TRUE,
    '{"tone":"contact"}'::jsonb
),
(
    'services.backend-api-development.hero',
    'hero',
    'services/backend-api-development',
    'Backend API Development for Reliable Digital Products',
    'API and system backend',
    'Build secure backend services, REST APIs, authentication, database flows, integrations, storage, caching, and operational logic for web, mobile, and SaaS products.',
    '/images/saas-dashboard-preview.png',
    '/#contact',
    'Discuss Backend API',
    10,
    TRUE,
    '{"eyebrow":"Backend API","stats":[{"label":"APIs","value":"REST"},{"label":"Security","value":"Auth Ready"},{"label":"Data","value":"Scalable"}]}'::jsonb
),
(
    'services.backend-api-development.overview',
    'service-detail',
    'services/backend-api-development',
    'Backend Services Designed for Real Usage',
    'Technical scope',
    'A strong backend keeps your product stable, secure, and easier to extend. We focus on clear API contracts, database design, validation, observability, caching, and integration readiness.',
    '',
    '/#contact',
    'Request Backend Plan',
    20,
    TRUE,
    '{"items":[{"title":"REST API development","subtitle":"API contract","description":"Build clean endpoints for web, mobile, admin panels, integrations, and internal services.","sort_order":10},{"title":"Authentication and roles","subtitle":"Secure access","description":"Implement login, refresh token flow, protected routes, permissions, and admin-only access where needed.","sort_order":20},{"title":"Database and storage","subtitle":"Data foundation","description":"Design relational data models, file storage access, migrations, and practical data workflows.","sort_order":30},{"title":"Caching and integrations","subtitle":"Performance ready","description":"Add caching, external API integrations, queues, notifications, and operational services based on project needs.","sort_order":40}]}'::jsonb
),
(
    'services.backend-api-development.process',
    'process',
    'services/backend-api-development',
    'Backend Development Process',
    'Implementation flow',
    'Backend development starts with data and business rules, then moves into API design, implementation, testing, and deployment readiness.',
    '',
    '',
    '',
    30,
    TRUE,
    '{"items":[{"title":"Data and rule mapping","subtitle":"Step 01","description":"Understand entities, access rules, workflow states, validation, reporting, and integration needs.","sort_order":10},{"title":"API and database design","subtitle":"Step 02","description":"Define endpoints, payloads, database schema, migrations, and service boundaries.","sort_order":20},{"title":"Implementation and testing","subtitle":"Step 03","description":"Build APIs, auth, storage, caching, integrations, and error handling with testable behavior.","sort_order":30},{"title":"Deployment readiness","subtitle":"Step 04","description":"Prepare environment variables, logs, cache behavior, security checks, and production usage notes.","sort_order":40}]}'::jsonb
),
(
    'services.backend-api-development.faq',
    'faq',
    'services/backend-api-development',
    'Backend API Questions',
    'FAQ',
    'Common backend development questions before starting implementation.',
    '',
    '',
    '',
    40,
    TRUE,
    '{"items":[{"title":"Can you build APIs for an existing frontend?","description":"Yes. The backend can be designed to support an existing frontend, mobile app, or admin panel.","sort_order":10},{"title":"Can you implement refresh token authentication?","description":"Yes. Authentication can include access tokens, refresh tokens, protected routes, and role-based access.","sort_order":20},{"title":"Can the backend use external storage or APIs?","description":"Yes. Storage, third-party APIs, notifications, payment gateways, and operational integrations can be added.","sort_order":30}]}'::jsonb
),
(
    'services.backend-api-development.contact',
    'section',
    'services/backend-api-development',
    'Need a Reliable Backend for Your Product?',
    'Contact Us',
    'Share your product flow, data model, API needs, and integration requirements. We will help define the backend architecture.',
    '',
    '',
    '',
    50,
    TRUE,
    '{"tone":"contact"}'::jsonb
)
ON CONFLICT (key) DO UPDATE SET
    type = EXCLUDED.type,
    placement = EXCLUDED.placement,
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    body = EXCLUDED.body,
    image_url = EXCLUDED.image_url,
    link_url = EXCLUDED.link_url,
    link_label = EXCLUDED.link_label,
    sort_order = EXCLUDED.sort_order,
    is_active = EXCLUDED.is_active,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();
