INSERT INTO website_contents (
    key,
    type,
    placement,
    title,
    subtitle,
    body,
    image_url,
    link_url,
    link_label,
    sort_order,
    is_active,
    metadata
) VALUES
(
    'home.gallery',
    'carousel',
    'home',
    'Explore the systems we can build and improve.',
    'Backend-managed carousel',
    'Use carousel content to highlight services, SaaS modules, product ideas, trusted delivery capabilities, or promotional campaigns from the admin panel.',
    '',
    '/#contact',
    'Start a Project',
    20,
    TRUE,
    '{"items":[{"title":"Custom business systems","subtitle":"Workflow-first development","background":"#ffffff","description":"Design and build internal systems that match your approvals, data, users, reports, and daily operational flow.","link_label":"Discuss system","link_url":"/#contact","image_url":"/images/saas-dashboard-preview.png","sort_order":10},{"title":"SaaS product foundations","subtitle":"Ready to scale","background":"#ffffff","description":"Launch SaaS products with role-based dashboards, backend APIs, content controls, subscription-ready structure, and deployment preparation.","link_label":"Plan SaaS","link_url":"/products","image_url":"/images/saas-dashboard-preview.png","sort_order":20},{"title":"Professional website content","subtitle":"Admin-managed pages","background":"#ffffff","description":"Manage hero sections, carousels, promos, trust blocks, product pages, and contact sections without editing frontend code.","link_label":"View content","link_url":"/about-us","image_url":"/images/saas-dashboard-preview.png","sort_order":30},{"title":"Integration and automation","subtitle":"Less manual work","background":"#ffffff","description":"Connect APIs, storage, notifications, dashboards, payment flows, and operational automation to reduce repeated tasks.","link_label":"Request automation","link_url":"/#contact","image_url":"/images/saas-dashboard-preview.png","sort_order":40}]}'::jsonb
),
(
    'about-us.capabilities-carousel',
    'carousel',
    'about-us',
    'Capabilities built for serious product delivery.',
    'What we can support',
    'A clean carousel for explaining the services, delivery strengths, and development scope that make SAE Technology Solution a dependable technology partner.',
    '',
    '/#contact',
    'Talk to Us',
    25,
    TRUE,
    '{"items":[{"title":"Discovery and product planning","subtitle":"Before development","background":"#ffffff","description":"Clarify business goals, user roles, workflows, integrations, risks, and the right delivery roadmap before implementation starts.","link_label":"Plan with us","link_url":"/#contact","image_url":"/images/saas-dashboard-preview.png","sort_order":10},{"title":"Full-stack implementation","subtitle":"Frontend and backend","background":"#ffffff","description":"Build polished interfaces, admin dashboards, APIs, database models, authentication, storage, and deployment-ready features.","link_label":"Start build","link_url":"/#contact","image_url":"/images/saas-dashboard-preview.png","sort_order":20},{"title":"Content-managed websites","subtitle":"Flexible pages","background":"#ffffff","description":"Use placement-based content to manage homepage, about page, product pages, campaigns, carousels, and contact sections professionally.","link_label":"View pages","link_url":"/about-us","image_url":"/images/saas-dashboard-preview.png","sort_order":30}]}'::jsonb
),
(
    'products.saecommerce.carousel',
    'carousel',
    'products/saecommerce',
    'SAECommerce modules ready to customize.',
    'Product carousel',
    'Showcase important product modules, extension points, and implementation value directly from website content placement products/saecommerce.',
    '',
    '/#contact',
    'Customize SAECommerce',
    25,
    TRUE,
    '{"items":[{"title":"Catalog and inventory flow","subtitle":"Commerce operations","background":"#ffffff","description":"Manage products, pricing, categories, stock movement, product visibility, and admin review workflows.","link_label":"Request module","link_url":"/#contact","image_url":"/images/saas-dashboard-preview.png","sort_order":10},{"title":"Orders and payments","subtitle":"Transaction workflow","background":"#ffffff","description":"Support order lifecycle, payment integration, customer notifications, fulfillment tracking, and internal approval rules.","link_label":"Discuss workflow","link_url":"/#contact","image_url":"/images/saas-dashboard-preview.png","sort_order":20},{"title":"Admin and reporting dashboard","subtitle":"Operational control","background":"#ffffff","description":"Give operators, managers, and owners clear dashboards for customers, orders, reports, roles, and business performance.","link_label":"Plan dashboard","link_url":"/#contact","image_url":"/images/saas-dashboard-preview.png","sort_order":30}]}'::jsonb
)
ON CONFLICT (key) DO UPDATE SET
    type = EXCLUDED.type,
    placement = EXCLUDED.placement,
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    body = EXCLUDED.body,
    image_url = EXCLUDED.image_url,
    link_url = EXCLUDED.link_url,
    link_label = EXCLUDED.link_label,
    sort_order = EXCLUDED.sort_order,
    is_active = EXCLUDED.is_active,
    metadata = EXCLUDED.metadata,
    deleted_at = NULL,
    updated_at = NOW();
