// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"net/http"

	"go-platform-core/internal/config"
	httpDelivery "go-platform-core/internal/delivery/http"
	"go-platform-core/internal/delivery/http/handler"
	recoverMiddleware "go-platform-core/internal/delivery/http/middleware/recover"
	"go-platform-core/internal/delivery/http/response"
	brokerDomain "go-platform-core/internal/domain/broker"
	"go-platform-core/internal/infrastructure/broker"
	"go-platform-core/internal/infrastructure/cache"
	"go-platform-core/internal/infrastructure/database"
	"go-platform-core/internal/infrastructure/email"
	"go-platform-core/internal/infrastructure/storage"
	"go-platform-core/internal/pkg/hash"
	"go-platform-core/internal/pkg/jwt"
	"go-platform-core/internal/pkg/logger"
	"go-platform-core/internal/pkg/tracing"
	"go-platform-core/internal/pkg/validator"
	"go-platform-core/internal/repository/content"
	"go-platform-core/internal/repository/user"
	"go-platform-core/internal/repository/website_setting"
	"go-platform-core/internal/usecase/auth"
	contentUsecase "go-platform-core/internal/usecase/content"
	"go-platform-core/internal/usecase/email_register"
	"go-platform-core/internal/usecase/publish_register"
	"go-platform-core/internal/usecase/upload"
	websiteSettingUsecase "go-platform-core/internal/usecase/website_setting"

	"gorm.io/gorm"
)

func InitServer() *http.Server {
	loggerService := logger.NewLogrus()
	cfg := config.Load()
	db := database.NewPostgresql(cfg)
	tracerProvider := tracing.NewTracerProvider()
	responder := response.NewJSONResponder()
	successResponse := response.NewSuccessResponse(responder)
	validatorService := validator.NewValidator()
	jwtService := jwt.NewJWT(cfg)
	hasher := hash.NewArgon2Hasher()

	conn := broker.NewRabbitConnection(cfg)
	publisher := broker.NewRabbitPublisher(conn, tracerProvider)
	registerPublisher := publish_register.NewUseCase(cfg, loggerService, publisher, tracerProvider)

	userRepository := user.NewPostgresqlRepository(db, tracerProvider)
	authUsecase := auth.NewUseCase(registerPublisher, loggerService, jwtService, userRepository, cfg, hasher, tracerProvider)
	authHandler := handler.NewAuthHandler(validatorService, authUsecase, responder, tracerProvider)

	redisConfig := config.LoadRedisConfig(cfg)
	redisClient := cache.NewRedisClient(redisConfig)
	cacheRepository := cache.NewRedisRepository(redisClient, tracerProvider)

	contentRepository := content.NewPostgresqlRepository(db, tracerProvider)
	contentService := contentUsecase.NewUseCase(loggerService, contentRepository, cacheRepository)
	contentHandler := handler.NewContentHandler(validatorService, contentService, successResponse, tracerProvider)

	websiteSettingRepository := website_setting.NewPostgresqlRepository(db, tracerProvider)
	websiteSettingService := websiteSettingUsecase.NewUseCase(loggerService, websiteSettingRepository, cacheRepository)
	websiteSettingHandler := handler.NewWebsiteSettingHandler(validatorService, websiteSettingService, successResponse, tracerProvider)

	s3Config := config.LoadS3Config(cfg)
	storageService := storage.NewS3Storage(s3Config, tracerProvider)
	fileUploadUsecase := upload.NewFileUploadUseCase(storageService, tracerProvider)
	storageHandler := handler.NewStorageHandlerImpl(fileUploadUsecase, successResponse, tracerProvider)

	healthHandler := handler.NewHealthHandler(responder)
	router := httpDelivery.NewRouter(
		websiteSettingHandler,
		contentHandler,
		jwtService,
		loggerService,
		healthHandler,
		authHandler,
		storageHandler,
	)
	recoverHandler := recoverMiddleware.NewMiddleware(loggerService, router, responder)
	return httpDelivery.NewServer(recoverHandler, cfg, router, tracerProvider)
}

func InitPostgresql() (*gorm.DB, error) {
	cfg := config.Load()
	return database.NewPostgresql(cfg), nil
}

func InitConsumer() brokerDomain.Consumer {
	cfg := config.Load()
	conn := broker.NewRabbitConnection(cfg)
	tracerProvider := tracing.NewTracerProvider()
	return broker.NewRabbitConsumer(conn, tracerProvider)
}

func InitRegisterEmailConsumer() *broker.UserConsumer {
	cfg := config.Load()
	emailSender := email.NewEmailSender(cfg)
	loggerService := logger.NewLogrus()
	registerUsecase := email_register.NewUseCase(emailSender, cfg, loggerService)
	return broker.NewUserConsumer(registerUsecase)
}
