// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/julienschmidt/httprouter"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/config"
	httpDelivery "github.com/bagusaditiasetiawan/saetechnology-be/internal/delivery/http"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/delivery/http/handler"
	recoverMiddleware "github.com/bagusaditiasetiawan/saetechnology-be/internal/delivery/http/middleware/recover"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/delivery/http/response"
	brokerDomain "github.com/bagusaditiasetiawan/saetechnology-be/internal/domain/broker"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/infrastructure/broker"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/infrastructure/cache"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/infrastructure/database"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/infrastructure/email"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/infrastructure/storage"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/pkg/hash"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/pkg/jwt"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/pkg/logger"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/pkg/tracing"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/pkg/validator"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/repository/contact"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/repository/content"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/repository/product"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/repository/user"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/repository/website_setting"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/usecase/auth"
	contactUsecase "github.com/bagusaditiasetiawan/saetechnology-be/internal/usecase/contact"
	contentUsecase "github.com/bagusaditiasetiawan/saetechnology-be/internal/usecase/content"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/usecase/email_register"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/usecase/publish_register"
	"github.com/bagusaditiasetiawan/saetechnology-be/internal/usecase/upload"
	productUsecase "github.com/bagusaditiasetiawan/saetechnology-be/internal/usecase/product"
	websiteSettingUsecase "github.com/bagusaditiasetiawan/saetechnology-be/internal/usecase/website_setting"
	"gorm.io/gorm"
	"net/http"
)

// Injectors from injector.go:

func InitServer() *http.Server {
	loggerLogger := logger.NewLogrus()
	validatorValidator := validator.NewValidator()
	configConfig := config.Load()
	db := database.NewPostgresql(configConfig)
	tracerProvider := tracing.NewTracerProvider()
	repository := website_setting.NewPostgresqlRepository(db, tracerProvider)
	redisConfig := config.LoadRedisConfig(configConfig)
	client := cache.NewRedisClient(redisConfig)
	cacheRepository := cache.NewRedisRepository(client, tracerProvider)
	useCase := websiteSettingUsecase.NewUseCase(loggerLogger, repository, cacheRepository)
	responder := response.NewJSONResponder()
	successResponse := response.NewSuccessResponse(responder)
	websiteSettingHandler := handler.NewWebsiteSettingHandler(validatorValidator, useCase, successResponse, tracerProvider)
	contentRepository := content.NewPostgresqlRepository(db, tracerProvider)
	contentUseCase := contentUsecase.NewUseCase(loggerLogger, contentRepository, cacheRepository)
	contentHandler := handler.NewContentHandler(validatorValidator, contentUseCase, successResponse, tracerProvider)
	contactRepository := contact.NewPostgresqlRepository(db, tracerProvider)
	contactUseCase := contactUsecase.NewUseCase(loggerLogger, contactRepository, cacheRepository)
	contactHandler := handler.NewContactHandler(validatorValidator, contactUseCase, successResponse, tracerProvider)
	productRepository := product.NewPostgresqlRepository(db, tracerProvider)
	productService := productUsecase.NewUseCase(loggerLogger, productRepository, cacheRepository)
	productHandler := handler.NewProductHandler(validatorValidator, productService, successResponse, tracerProvider)
	jwtJWT := jwt.NewJWT(configConfig)
	healthHandler := handler.NewHealthHandler(responder)
	conn := broker.NewRabbitConnection(configConfig)
	publisher := broker.NewRabbitPublisher(conn, tracerProvider)
	publish_registerUseCase := publish_register.NewUseCase(configConfig, loggerLogger, publisher, tracerProvider)
	userRepository := user.NewPostgresqlRepository(db, tracerProvider)
	hasher := hash.NewArgon2Hasher()
	usecase := auth.NewUseCase(publish_registerUseCase, loggerLogger, jwtJWT, userRepository, configConfig, hasher, tracerProvider)
	authHandler := handler.NewAuthHandler(validatorValidator, usecase, responder, tracerProvider)
	s3Config := config.LoadS3Config(configConfig)
	storageStorage := storage.NewS3Storage(s3Config, tracerProvider)
	fileUploadUseCase := upload.NewFileUploadUseCase(storageStorage, tracerProvider)
	storageHandler := handler.NewStorageHandlerImpl(fileUploadUseCase, successResponse, tracerProvider)
	router := httpDelivery.NewRouter(websiteSettingHandler, contentHandler, contactHandler, productHandler, jwtJWT, loggerLogger, healthHandler, authHandler, storageHandler)
	middleware := recoverMiddleware.NewMiddleware(loggerLogger, router, responder)
	server := httpDelivery.NewServer(middleware, configConfig, router, tracerProvider)
	return server
}

func InitPostgresql() (*gorm.DB, error) {
	configConfig := config.Load()
	db := database.NewPostgresql(configConfig)
	return db, nil
}

func InitConsumer() brokerDomain.Consumer {
	configConfig := config.Load()
	conn := broker.NewRabbitConnection(configConfig)
	tracerProvider := tracing.NewTracerProvider()
	consumer := broker.NewRabbitConsumer(conn, tracerProvider)
	return consumer
}

func InitRegisterEmailConsumer() *broker.UserConsumer {
	configConfig := config.Load()
	emailSender := email.NewEmailSender(configConfig)
	loggerLogger := logger.NewLogrus()
	useCase := email_register.NewUseCase(emailSender, configConfig, loggerLogger)
	userConsumer := broker.NewUserConsumer(useCase)
	return userConsumer
}

// injector.go:

var loggerSet = wire.NewSet(logger.NewLogrus)

var cacheSet = wire.NewSet(config.LoadRedisConfig, cache.NewRedisClient, cache.NewRedisRepository)

var registerEmailSet = wire.NewSet(broker.NewRabbitConnection, broker.NewRabbitPublisher, publish_register.NewUseCase)

var authHandlerSet = wire.NewSet(user.NewPostgresqlRepository, hash.NewArgon2Hasher, registerEmailSet, auth.NewUseCase, handler.NewAuthHandler)

var contentHandlerSet = wire.NewSet(content.NewPostgresqlRepository, contentUsecase.NewUseCase, handler.NewContentHandler)

var contactHandlerSet = wire.NewSet(contact.NewPostgresqlRepository, contactUsecase.NewUseCase, handler.NewContactHandler)

var productHandlerSet = wire.NewSet(product.NewPostgresqlRepository, productUsecase.NewUseCase, handler.NewProductHandler)

var websiteSettingHandlerSet = wire.NewSet(website_setting.NewPostgresqlRepository, websiteSettingUsecase.NewUseCase, handler.NewWebsiteSettingHandler)

var storageHandlerSet = wire.NewSet(config.LoadS3Config, storage.NewS3Storage, upload.NewFileUploadUseCase, handler.NewStorageHandlerImpl)

var httpSet = wire.NewSet(response.NewJSONResponder, response.NewSuccessResponse, handler.NewHealthHandler, httpDelivery.NewRouter, recoverMiddleware.NewMiddleware, wire.Bind(new(http.Handler), new(*httprouter.Router)), httpDelivery.NewServer)
