INSERT INTO website_settings (
    id,
    site_name,
    tagline,
    email,
    phone,
    address,
    primary_color,
    secondary_color,
    accent_color,
    background_color,
    surface_color,
    text_color,
    muted_text_color,
    border_color,
    metadata,
    created_at,
    updated_at
) VALUES (
    '00000000-0000-0000-0000-000000000100',
    'SAE Technology Solution',
    'Professional custom software, SaaS platforms, and digital systems built for teams that need reliability, speed, and scalability.',
    'hello@saetech.local',
    '+62 812 0000 0000',
    'Jakarta, Indonesia',
    '#142761',
    '#eef2ff',
    '#244b4c',
    '#f7f9fc',
    '#ffffff',
    '#0f172a',
    '#64748b',
    '#e2e8f0',
    '{"seo_title":"SAE Technology Solution | Custom Software, SaaS, and System Development","seo_description":"SAE Technology Solution builds professional custom software, SaaS products, admin dashboards, and backend-integrated systems designed to support modern business operations."}'::jsonb,
    NOW(),
    NOW()
)
ON CONFLICT ((true)) DO UPDATE SET
    site_name = EXCLUDED.site_name,
    tagline = EXCLUDED.tagline,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    address = EXCLUDED.address,
    primary_color = EXCLUDED.primary_color,
    secondary_color = EXCLUDED.secondary_color,
    accent_color = EXCLUDED.accent_color,
    background_color = EXCLUDED.background_color,
    surface_color = EXCLUDED.surface_color,
    text_color = EXCLUDED.text_color,
    muted_text_color = EXCLUDED.muted_text_color,
    border_color = EXCLUDED.border_color,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();

INSERT INTO website_contents (
    key,
    type,
    placement,
    title,
    subtitle,
    body,
    image_url,
    link_url,
    link_label,
    sort_order,
    is_active,
    metadata,
    created_at,
    updated_at
) VALUES
(
    'home.hero',
    'hero',
    'home',
    'Build custom systems and SaaS products with confidence.',
    'Custom software development',
    'A professional, production-ready Next.js experience designed to promote your custom system development, SaaS products, and backend-driven digital solutions.',
    '/images/saas-dashboard-preview.png',
    '#contact',
    'Start Your Project',
    10,
    TRUE,
    '{"eyebrow":"Backend-powered website"}'::jsonb,
    NOW(),
    NOW()
),
(
    'home.announcement',
    'announcement',
    'home',
    'Your new website content system is ready.',
    'Announcement',
    'Manage hero, banner, promo, service, and contact content directly from backend data with a workflow built for professional delivery.',
    '',
    '/admin/content',
    'Open Dashboard',
    15,
    TRUE,
    '{"tone":"info"}'::jsonb,
    NOW(),
    NOW()
),
(
    'home.gallery',
    'section',
    'home',
    'Sections controlled from backend.',
    'Website content management',
    'Every active item below comes from `website_contents`. When backend data is unavailable, the page keeps a safe and professional fallback experience.',
    '',
    '/admin/content',
    'Manage Website Content',
    20,
    TRUE,
    '{"layout":"grid"}'::jsonb,
    NOW(),
    NOW()
),
(
    'home.banner',
    'banner',
    'home',
    'Custom systems, dashboards, and SaaS solutions in one delivery flow.',
    'Product delivery',
    'Use this banner to highlight your software services, key differentiators, or priority delivery capabilities.',
    '',
    '#services',
    'View Services',
    30,
    TRUE,
    '{"tone":"brand"}'::jsonb,
    NOW(),
    NOW()
),
(
    'home.services',
    'section',
    'home',
    'From idea to a maintainable, scalable product.',
    'Software development services',
    'Product strategy, custom system development, SaaS builds, admin panels, automation, content APIs, and deployment-ready architecture.',
    '',
    '#contact',
    'Discuss Your Build',
    40,
    TRUE,
    '{"items":[{"title":"Custom Business Systems","subtitle":"Built around your workflow","background":"#ffffff","description":"<p>Tailored software systems that streamline operations, support decision-making, and grow with your business.</p>","link_label":"Discuss Project","link_url":"#contact","image_url":"","sort_order":10},{"title":"SaaS Product Development","subtitle":"Modern product delivery","background":"#ffffff","description":"<p>Scalable SaaS platforms with clear architecture, maintainable code, and user-focused experiences.</p>","link_label":"Explore SaaS","link_url":"#contact","image_url":"","sort_order":20},{"title":"Admin Dashboards","subtitle":"Operational control panels","background":"#ffffff","description":"<p>Professional dashboards for managing users, content, settings, workflows, and internal operations.</p>","link_label":"See Dashboard","link_url":"#contact","image_url":"","sort_order":30},{"title":"Backend APIs","subtitle":"Reliable data layer","background":"#ffffff","description":"<p>Structured APIs for authentication, content delivery, uploads, settings, integrations, and automation.</p>","link_label":"Review APIs","link_url":"#contact","image_url":"","sort_order":40}]}'::jsonb,
    NOW(),
    NOW()
),
(
    'home.promo',
    'promo',
    'home',
    'Launch faster with a backend-ready content model.',
    'Professional software delivery',
    'Keep copy, colors, images, and publish schedules editable without touching production code.',
    '',
    '/admin/settings',
    'Adjust Theme',
    50,
    TRUE,
    '{"highlight":"Theme variables are generated from website_settings."}'::jsonb,
    NOW(),
    NOW()
),
(
    'home.contact',
    'section',
    'home',
    'Tell us what you want to build.',
    'Project brief',
    'Share your idea and we will help define the landing page, dashboard, admin content, and backend integration path for your custom software or SaaS product.',
    '',
    'mailto:hello@saetech.local',
    'Send Brief',
    60,
    TRUE,
    '{"variant":"contact"}'::jsonb,
    NOW(),
    NOW()
)
ON CONFLICT (key) DO UPDATE SET
    type = EXCLUDED.type,
    placement = EXCLUDED.placement,
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    body = EXCLUDED.body,
    image_url = EXCLUDED.image_url,
    link_url = EXCLUDED.link_url,
    link_label = EXCLUDED.link_label,
    sort_order = EXCLUDED.sort_order,
    is_active = EXCLUDED.is_active,
    metadata = EXCLUDED.metadata,
    deleted_at = NULL,
    updated_at = NOW();
