INSERT INTO website_settings (
    id,
    site_name,
    tagline,
    email,
    phone,
    address,
    primary_color,
    secondary_color,
    accent_color,
    background_color,
    surface_color,
    text_color,
    muted_text_color,
    border_color,
    metadata,
    created_at,
    updated_at
) VALUES (
    '00000000-0000-0000-0000-000000000100',
    'SAE Technology Solution',
    'Custom app, SaaS product, and digital operation systems.',
    'hello@saetech.local',
    '+62 812 0000 0000',
    'Jakarta, Indonesia',
    '#142761',
    '#eef2ff',
    '#244b4c',
    '#f7f9fc',
    '#ffffff',
    '#0f172a',
    '#64748b',
    '#e2e8f0',
    '{"seo_title":"SAE Technology Solution | SaaS & Custom App Development","seo_description":"SAE Technology Solution builds clean SaaS landing pages, admin dashboards, custom apps, and backend-integrated digital systems."}'::jsonb,
    NOW(),
    NOW()
)
ON CONFLICT ((true)) DO UPDATE SET
    site_name = EXCLUDED.site_name,
    tagline = EXCLUDED.tagline,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    address = EXCLUDED.address,
    primary_color = EXCLUDED.primary_color,
    secondary_color = EXCLUDED.secondary_color,
    accent_color = EXCLUDED.accent_color,
    background_color = EXCLUDED.background_color,
    surface_color = EXCLUDED.surface_color,
    text_color = EXCLUDED.text_color,
    muted_text_color = EXCLUDED.muted_text_color,
    border_color = EXCLUDED.border_color,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();

INSERT INTO website_contents (
    key,
    type,
    placement,
    title,
    subtitle,
    body,
    image_url,
    link_url,
    link_label,
    sort_order,
    is_active,
    metadata,
    created_at,
    updated_at
) VALUES
(
    'home.hero',
    'hero',
    'home',
    'Build sharper SaaS products with cleaner systems.',
    'Backend-powered website',
    'A production-ready Next.js experience backed by clean components, flexible content, and theme variables from your website settings.',
    '/images/saas-dashboard-preview.png',
    '#contact',
    'Start Project',
    10,
    TRUE,
    '{"eyebrow":"Backend-powered website"}'::jsonb,
    NOW(),
    NOW()
),
(
    'home.announcement',
    'announcement',
    'home',
    'New admin content system is live.',
    'Announcement',
    'Manage hero, banner, promo, services, and contact content directly from backend data.',
    '',
    '/admin/content',
    'Open Admin',
    15,
    TRUE,
    '{"tone":"info"}'::jsonb,
    NOW(),
    NOW()
),
(
    'home.gallery',
    'section',
    'home',
    'Sections controlled from backend.',
    'Website Content',
    'Every active item below comes from website_contents. When backend data is empty, the page keeps a safe fallback.',
    '',
    '/admin/content',
    'Manage Content',
    20,
    TRUE,
    '{"layout":"grid"}'::jsonb,
    NOW(),
    NOW()
),
(
    'home.banner',
    'banner',
    'home',
    'Custom apps, dashboards, and automation in one delivery flow.',
    'Product delivery',
    'Use this banner for key positioning, product highlights, or limited-time service announcements.',
    '',
    '#services',
    'View Services',
    30,
    TRUE,
    '{"tone":"brand"}'::jsonb,
    NOW(),
    NOW()
),
(
    'home.services',
    'section',
    'home',
    'From idea to maintainable product code.',
    'Services',
    'Product design, full-stack development, admin panels, automation, content APIs, and deployment-ready architecture.',
    '',
    '#contact',
    'Discuss Your Build',
    40,
    TRUE,
    '{"items":[{"title":"Landing Pages","subtitle":"High-converting website pages","background":"#ffffff","description":"<p>SEO-friendly pages with flexible copy, CTA, media, and publish-ready content blocks.</p>","link_label":"Explore","link_url":"#contact","image_url":"","sort_order":10},{"title":"Admin Dashboards","subtitle":"Operational control panels","background":"#ffffff","description":"<p>Clean dashboards for managing users, content, settings, workflow, and internal operations.</p>","link_label":"Explore","link_url":"#contact","image_url":"","sort_order":20},{"title":"Backend APIs","subtitle":"Reliable data layer","background":"#ffffff","description":"<p>Structured APIs for authentication, content delivery, uploads, settings, and integrations.</p>","link_label":"Explore","link_url":"#contact","image_url":"","sort_order":30},{"title":"Automation","subtitle":"Less repeated work","background":"#ffffff","description":"<p>Automated flows for admin tasks, notifications, content updates, and business process handoff.</p>","link_label":"Explore","link_url":"#contact","image_url":"","sort_order":40}]}'::jsonb,
    NOW(),
    NOW()
),
(
    'home.promo',
    'promo',
    'home',
    'Launch faster with a backend-ready content model.',
    'Promo',
    'Keep copy, colors, images, and publish schedules editable without touching production code.',
    '',
    '/admin/settings',
    'Adjust Theme',
    50,
    TRUE,
    '{"highlight":"Theme variables are generated from website_settings."}'::jsonb,
    NOW(),
    NOW()
),
(
    'home.contact',
    'section',
    'home',
    'Tell us what you want to build.',
    'Project brief',
    'Share your product idea and we will help map the landing page, dashboard, admin content, and backend integration path.',
    '',
    'mailto:hello@saetech.local',
    'Send Brief',
    60,
    TRUE,
    '{"variant":"contact"}'::jsonb,
    NOW(),
    NOW()
)
ON CONFLICT (key) DO UPDATE SET
    type = EXCLUDED.type,
    placement = EXCLUDED.placement,
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    body = EXCLUDED.body,
    image_url = EXCLUDED.image_url,
    link_url = EXCLUDED.link_url,
    link_label = EXCLUDED.link_label,
    sort_order = EXCLUDED.sort_order,
    is_active = EXCLUDED.is_active,
    metadata = EXCLUDED.metadata,
    deleted_at = NULL,
    updated_at = NOW();
